org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.log.org.apache.kafka.common.utils.AppInfoParser=error
org.slf4j.simpleLogger.log.org.apache.kafka.clients.producer.ProducerConfig=error
org.slf4j.simpleLogger.log.org.apache.kafka.clients.Metadata=warn
org.slf4j.simpleLogger.log.org.apache.kafka.common.metrics.Metrics=warn
org.slf4j.simpleLogger.log.org.apache.kafka.clients.producer.KafkaProducer=warn
org.slf4j.simpleLogger.log.io.confluent.kafka.serializers=warn
